[workspace]
resolver = "2"
members = ["core", "src-tauri", "tui"]

[workspace.package]
version = "0.2.0"
edition = "2021"
license = "MIT"

# Read the optimization guideline for more details: https://tauri.app/concept/size/#cargo-configuration
[profile.release]
codegen-units = 1
lto = true
opt-level = 3
panic = "abort"
strip = true
